### ISSUE TITLE
It's really difficult to understand how to use the plugin

### ISSUE THREAD

**Issue by for-coursera** [maxigit/vim-xrange#1]
What is `<toc>`? What is `<ls>`? And so on :)

Some proper documentation or at least a video would be really helpful (I watched some emacs org-babel videos on YouTube, and still couldn't figure out how to use `vim-xrange`)

Sorry for this feedback, your plugin really seems like a useful one, just a bit too mysterious :)

**Comment by maxigit** [comment]
<toc> and <ls> are arbitrary names to delimit ranges (the toc range start
at <toc> and end with </toc>).
When executed it is filled the table of content of the actual readme file.

The doc is supposed to be interactive, but I understand that to be able to
follow it you need first to install the plugin.

However, I think it's a fair comment and I'll try to do a video in the
coming days.

**Comment by maxigit** [comment]
Updated the README with some video.
