### ISSUE TITLE
Neovim Compatability

### ISSUE THREAD

**Issue by Tokazama** [maxigit/vim-xrange#2]
I get a whole bunch of errors when I open a file in neovim if this plugin is active.
![image](https://user-images.githubusercontent.com/13888485/76170149-9baad500-6155-11ea-8418-4e8844afc42c.png)

**Comment by maxigit** [comment]
Neovim doesn't support default argument in function (as old vim version).

**Comment by maxigit** [comment]
It should be fixed. Could you let me know if you encounter any problems ?

**Comment by Tokazama** [comment]
I haven't tested anything out yet but I can confirm it doesn't error now. Thanks!
